### ISSUE TITLE
How to work organism-react-scroll-nav in modal?

### ISSUE THREAD

**Issue by lakshmisanthi** [react-atomic/organism-react-scroll-nav#1]
HI, I am using organism-react-scroll-nav. it's working in good. but I want scroll spy in modal box.
In modal, it's not working, how can i do it. 

Please help me to fix it.
Thanks in advance.

**Comment by HillLiu** [comment]
@lakshmisanthi 
do you mean you want work on modal such as following component?
https://semantic-ui.com/modules/modal.html

Also you don't want scroll with default page-scroll and use modal div's scroll instead, is it?

**Comment by HillLiu** [comment]
close it when library also support modal.
